### ISSUE TITLE
should we consider to to rename the component given that PHP7 makes Resource a reserved word

### ISSUE THREAD

**Issue by lsmith77** [symfony-cmf/resource#10]
Its obviously atm not an issue .. but feels iffy to have a namespace named after a reserved word

**Comment by dantleech** [comment]
Maybe we should wait and see what @webmozart decides to do with the Puli resource.
It could make the most sense to follow that example.

**Comment by webmozart** [comment]
We decided to rename `Resource` to `PuliResource` for Puli.

**Comment by webmozart** [comment]
btw. using "Resource" as namespace name is fine

**Comment by dantleech** [comment]
@lsmith77 can this be closed? we only use `Resource` as a namespace, which should be fine.
