### ISSUE TITLE
Standardize the retrieval of URLs relating to a specific resource.

### ISSUE THREAD

**Issue by dantleech** [symfony-cmf/resource#18]
The ResourceRestBundle currently has the concept of "enhancers" which add
fields such as the URL to edit or create the underlying resource payload.

I would like to push this back a level: this information is useful more
gernerally, for example when building an admin interface that doesn't need REST
and where you need the edit/view/create/delete URLs.

Puli already has the concept of `Metadata` but it is metadata _from_ the
resource, we want metadata which is "over" the resource - i.e. the URLs of the
admin system.

So I am proposing something like:

```
class SonataMetadata implements HtmlAdminMetadataInterface
{
   /**
    * Return the edit URL for the resources payload.
    *
    * @return string|null
    */
   public function getHtmlEditUrl();

   /**
    * Return the remove URL for the resources payload.

    * @return string|null
    */
   public function getHtmlRemoveUrl();

   /**
    * Return the add URL for the resources payload using this item as a parent.

    * @return string|null
    */
   public function getHtmlAddChildUrl();
}
```

or:

``` php
class SyliusMetadata implements AdminMetadataInterface
{
    public function __construct(Router $router)
    {
        // ... 
    }

    public function supports()
    {
        return [
            AdminMetadata::HTML_EDIT,
            AdminMetadata::HTML_REMOVE,
            AdminMetadata::HTML_ADD_CHILD,
            AdminMetadata::REST_CREATE,
            AdminMetadata::REST_REMOVE,
        ];
    }

    public function get($name)
    {
         switch ($name) {
             case AdminMetadata::HTML_EDIT:
                  return $this->router->generate(' ... ');
                  break;
        }

        throw ..
    }
}
```

Where we would have a factory system using drivers similar to the current `SonataEnhancer` in the ResourceRestBundle.

Very much open to other ideas.

/cc @WouterJ @dbu @lsmith77

**Comment by dbu** [comment]
looks reasonable. my only doubt is about the use case. is this to handle systems with mixed html admins? or to integrate something like sonata admin or sylius admin into a custom application? because sonata admin already has all the tools to build admins for all things managed with sonata. can you elaborate on the use case, please?

**Comment by dantleech** [comment]
The primary use case is the TreeBrowser, it requires the links to the create, edit and (delete?) URLs for the node (when that node represents an Entity managed by Sonata).

We currently handle this in the ResourceRestBundle, however you shouldn't need to use the REST API to get this information, as it can at least be useful in a custom server-side admin.

It is not likely that both Sylius and Sonata are used at the same time, but that would also be possible here, as would being able to provide edition URLs for standard, non-CMF, resources - such as files.

The use case that is driving my effort here is a server-side tree browser I have built, which doesn't use the ResourceRestBundle, but still requires the information about the CRUD URLs etc.

**Comment by dantleech** [comment]
Also see the WIP: https://github.com/symfony-cmf/resource/pull/19https://github.com/symfony-cmf/resource/pull/19

**Comment by dbu** [comment]
ah, okay. well i guess if this is not a huge system (and it looks like its not that large) i am convinced now that this makes sense.
