### ISSUE TITLE
Move admin enhancers out of here.

### ISSUE THREAD

**Issue by dantleech** [symfony-cmf/resource#34]
The Sonata Enhancer can live in the as-yet-not-existing CmfSonataAdminBundle.

The Sylius Enhancer should live in an equivilent place.

These are integration enhancers, and should be part of an integration package which has all of the relevant dependencies.

**Comment by ElectricMaxxx** [comment]
As the sonata-admin-integration-bundle exists now it is now open for the enhancer.

**Comment by ElectricMaxxx** [comment]
So i will take sonata first.

**Comment by ElectricMaxxx** [comment]
@dantleech @wouterj what to do with the sylius, remove first?
where to add?

**Comment by wouterj** [comment]
Keep in here I would say

**Comment by ElectricMaxxx** [comment]
but i need to revert the commit then :-)
