### ISSUE TITLE
Extract Description into separate component.

### ISSUE THREAD

**Issue by dantleech** [symfony-cmf/resource#36]
All of the current desciption enhancers act upon the Payload - i.e. they don't really care about the resource.

This is not to say that enhancers _can't_ act on the resource itself (e.g. actual files) but just that currently none of the do.

We can extract the Description stuff into a separate component that acts upon objects of any type, not just `PuliResource` instances.

`CmfResource` instances can still be supported - we just make a `PuliResource` enhancer which is a "proxy" to the descrition for the payload and other Puli resources (e.g. FileResource) can still be handled.

**Comment by dantleech** [comment]
If moving we should also adopt class based descriptors: https://github.com/symfony-cmf/resource/issues/25

**Comment by dantleech** [comment]
Why was this closed?

**Comment by wouterj** [comment]
It's now distracted in a component in Psiphp, isn't it? And using that component once it's stable is mentioned in https://github.com/symfony-cmf/resource/issues/38

**Comment by dantleech** [comment]
ok, makes sense :)
